In [1]:
import pandas as pd
import numpy as np
import math
import matplotlib.pyplot as plt
import seaborn as sns
from scipy.stats import vonmises
import scipy.stats
import random
import ruptures as rpt
from sklearn.metrics import confusion_matrix
import warnings
warnings.filterwarnings('ignore')

In [2]:
# About the simulate data:
# Four time point: wakeup, first-meal, last-meal, sleep
# Monday to Friday are around 6am, 8am, 6pm, 9pm
# Saturday and Sunday are around 7am, 9am, 7pm, 10pm
# Noise control in 0.25h
# penalty = 1
# 6 months, 24 weeks, 24*7=168 days

In [3]:
wakeup = []
for i in range(24):
    for j in range(5):
        numberweekday = round(random.uniform(5.75,6.25), 2)
        wakeup.append(numberweekday)
        j += 1
    for k in range(2):
        numberweekend = round(random.uniform(6.75,7.25), 2)
        wakeup.append(numberweekend)
        k += 1
    i += 1
    

firstMeal = []
for i in range(24):
    for j in range(5):
        numberweekday = round(random.uniform(7.75,8.25), 2)
        firstMeal.append(numberweekday)
        j += 1
    for k in range(2):
        numberweekend = round(random.uniform(8.75,9.25), 2)
        firstMeal.append(numberweekend)
        k += 1
    i += 1
    

lastMeal = []
for i in range(24):
    for j in range(5):
        numberweekday = round(random.uniform(17.75,18.25), 2)
        lastMeal.append(numberweekday)
        j += 1
    for k in range(2):
        numberweekend = round(random.uniform(18.75,19.25), 2)
        lastMeal.append(numberweekend)
        k += 1
    i += 1
    

sleep = []
for i in range(24):
    for j in range(5):
        numberweekday = round(random.uniform(20.75,21.25), 2)
        sleep.append(numberweekday)
        j += 1
    for k in range(2):
        numberweekend = round(random.uniform(21.75,22.25), 2)
        sleep.append(numberweekend)
        k += 1
    i += 1

In [4]:
df = pd.read_csv("start.csv")
df['wakeup'] = wakeup
df['firstMeal'] = firstMeal
df['lastMeal'] = lastMeal
df['sleep'] = sleep
df

     day    weekday  wakeup  firstMeal  lastMeal  sleep
0      1     Monday    6.11       7.81     18.16  20.98
1      2    Tuesday    6.21       7.84     18.06  20.99
2      3  Wednesday    5.98       8.00     18.09  21.08
3      4   Thursday    6.24       7.95     18.12  21.05
4      5     Friday    5.92       8.19     17.97  20.86
..   ...        ...     ...        ...       ...    ...
163  164  Wednesday    5.96       8.07     18.15  20.82
164  165   Thursday    6.16       7.80     18.15  20.79
165  166     Friday    5.99       7.95     17.92  20.98
166  167   Saturday    6.88       9.09     18.96  21.98
167  168     Sunday    6.96       9.24     18.86  21.81

[168 rows x 6 columns]